from __future__ import annotations

from datetime import datetime, timedelta, timezone

import pandas as pd


def dataframe_to_fhir_observations(
    frame: pd.DataFrame,
    *,
    patient_reference: str = "Patient/virtual-patient",
    start_time: datetime | None = None,
) -> list[dict]:
    """Convert simulated glucose values to minimal FHIR R5 Observation resources."""
    start_time = start_time or datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
    resources: list[dict] = []
    for row in frame.itertuples(index=False):
        timestamp = start_time + timedelta(minutes=int(row.minute))
        resources.append(
            {
                "resourceType": "Observation",
                "status": "final",
                "category": [
                    {
                        "coding": [
                            {
                                "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                                "code": "laboratory",
                                "display": "Laboratory",
                            }
                        ]
                    }
                ],
                "code": {
                    "coding": [
                        {
                            "system": "http://loinc.org",
                            "code": "15074-8",
                            "display": "Glucose [Moles/volume] in Blood",
                        }
                    ],
                    "text": "Simulated glucose",
                },
                "subject": {"reference": patient_reference},
                "effectiveDateTime": timestamp.isoformat(),
                "valueQuantity": {
                    "value": round(float(row.glucose_mg_dl), 1),
                    "unit": "mg/dL",
                    "system": "http://unitsofmeasure.org",
                    "code": "mg/dL",
                },
                "note": [{"text": "Synthetic observation generated by DiabetesTwin-AI; not a clinical measurement."}],
            }
        )
    return resources
