# ruff: noqa: E501

DASHBOARD_HTML = r'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#00685f" />
  <meta name="description" content="DiabetesTwin-AI predictive digital twin research dashboard" />
  <title>DiabetesTwin-AI · Metabolic Digital Twin</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@200..700,0..1&display=swap" rel="stylesheet" />
  <style>
    :root {
      --bg:#f7f9fb; --surface:#fff; --surface-low:#f2f4f6; --surface-high:#e6e8ea;
      --ink:#191c1e; --muted:#5b6664; --line:#dce5e2; --line-strong:#bcc9c6;
      --primary:#00685f; --primary2:#008378; --primary-soft:#e5f5f2; --cyan:#06b6d4; --cyan-soft:#e9faff;
      --green:#36a45d; --green-soft:#eaf7ef; --amber:#c48700; --amber-soft:#fff7df; --red:#ba1a1a; --red-soft:#ffefed;
      --nav:264px; --shadow:0 10px 28px rgba(15,23,42,.06); --shadow-lg:0 24px 60px rgba(0,104,95,.10);
    }
    *{box-sizing:border-box} html{scroll-behavior:smooth} body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}
    button,input,select{font:inherit} button{cursor:pointer} a{color:inherit;text-decoration:none} .material-symbols-outlined{font-size:21px;line-height:1}
    .app{min-height:100vh}.sidebar{position:fixed;left:0;top:0;bottom:0;width:var(--nav);padding:22px 16px;background:#f1f4f5;border-right:1px solid var(--line-strong);display:flex;flex-direction:column;z-index:40}
    .brand{display:flex;align-items:center;gap:12px;padding:2px 8px 26px}.logo{width:42px;height:42px;border-radius:14px;display:grid;place-items:center;background:linear-gradient(145deg,#00685f,#06b6d4);color:white;font-weight:800;box-shadow:0 9px 22px rgba(0,104,95,.18)}
    .brand strong{display:block;color:var(--primary);font-size:18px;letter-spacing:-.02em}.brand small{display:block;color:#41514e;margin-top:2px;font-size:11px;letter-spacing:.06em;text-transform:uppercase}
    .nav{display:flex;flex-direction:column;gap:5px;overflow:auto}.nav-btn{border:0;background:transparent;display:flex;align-items:center;gap:13px;text-align:left;width:100%;padding:12px 13px;border-radius:12px;color:#32413f;font-size:13px;font-weight:600;transition:.16s ease}
    .nav-btn:hover{background:#e6eceb;color:var(--primary)}.nav-btn.active{background:#57dffe;color:#00343c;box-shadow:inset 0 0 0 1px rgba(0,104,122,.08)}.nav-btn .material-symbols-outlined{font-size:20px}
    .side-foot{margin-top:auto;border-top:1px solid var(--line-strong);padding-top:13px}.side-status{margin:10px 5px 0;padding:11px;border-radius:12px;background:white;border:1px solid var(--line);font-size:10px;color:var(--muted);line-height:1.45}.side-status strong{color:var(--ink)}
    .shell{margin-left:var(--nav);min-height:100vh}.topbar{position:sticky;top:0;z-index:30;height:68px;background:rgba(247,249,251,.88);backdrop-filter:blur(18px);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 28px}
    .top-left{display:flex;align-items:center;gap:9px;color:var(--muted);font-size:12px}.top-actions{display:flex;align-items:center;gap:10px}.sync-pill{display:inline-flex;align-items:center;gap:8px;background:#e8eceb;border:1px solid #d8e1df;padding:8px 12px;border-radius:999px;font-size:12px;font-weight:700}.dot{width:9px;height:9px;border-radius:50%;background:#65b238;box-shadow:0 0 0 4px rgba(101,178,56,.10)}
    .icon-btn{width:38px;height:38px;border-radius:12px;border:1px solid transparent;background:transparent;color:#455552;display:grid;place-items:center}.icon-btn:hover{background:white;border-color:var(--line)}.avatar{width:34px;height:34px;border-radius:50%;background:linear-gradient(145deg,#dcebea,#b9dbd7);display:grid;place-items:center;color:var(--primary);font-weight:800;border:2px solid white;box-shadow:0 2px 8px rgba(0,0,0,.08)}
    main{max-width:1440px;margin:0 auto;padding:32px 28px 70px}.page{display:none;animation:pageIn .22s ease}.page.active{display:block}@keyframes pageIn{from{opacity:0;transform:translateY(5px)}to{opacity:1;transform:none}}
    .eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:var(--primary);font-weight:800}.page-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:24px}.page-head h1{font-size:34px;line-height:1.08;letter-spacing:-.035em;margin:5px 0 5px}.page-head p{margin:0;color:var(--muted);font-size:14px;line-height:1.55}.head-actions{display:flex;gap:9px;align-items:center;flex-wrap:wrap;justify-content:flex-end}
    .chip{display:inline-flex;align-items:center;gap:6px;padding:7px 10px;border-radius:999px;border:1px solid var(--line);background:white;font-size:10.5px;font-weight:700;color:#42514f}.chip.primary{background:var(--primary-soft);border-color:#cce5e0;color:var(--primary)}.chip.cyan{background:var(--cyan-soft);border-color:#c7f1f8;color:#00687a}.chip.warn{background:var(--amber-soft);border-color:#f1dfaa;color:#745400}
    .card{background:var(--surface);border:1px solid var(--line);border-radius:20px;box-shadow:var(--shadow)}.card.soft{background:#fbfdfd}.card-pad{padding:20px}.card-pad-lg{padding:26px}.section-title{font-size:16px;font-weight:800;letter-spacing:-.015em}.section-sub{font-size:11px;color:var(--muted);margin-top:4px;line-height:1.5}.grid{display:grid;gap:14px}.kpi-grid{grid-template-columns:repeat(6,minmax(0,1fr));margin:16px 0 28px}.kpi{padding:16px 17px;min-height:118px}.kpi-label{display:flex;align-items:center;justify-content:space-between;color:var(--muted);font-size:10px;font-weight:700}.kpi-value{font-size:26px;font-weight:800;letter-spacing:-.04em;margin-top:12px;font-variant-numeric:tabular-nums}.kpi-sub{font-size:9.5px;color:var(--muted);margin-top:6px}.trend{font-size:10px;font-weight:700}.trend.good{color:var(--green)}.trend.warn{color:var(--amber)}
    .hero-overview{position:relative;min-height:510px;overflow:hidden;background:#eef5f4}.hero-img{position:absolute;inset:0;background:linear-gradient(90deg,rgba(247,249,251,.25),rgba(247,249,251,.10)),url('https://lh3.googleusercontent.com/aida-public/AB6AXuC7MqmRs-s7-LSvnpSt9KABqopYy3sp0OhLwsd34srceyDwciTL6svXlMm7gZ_i8XlDXPcRKhzx8Xq5UAEvbljwzk8ZUBEWqAhCq1WzhElaJjxGYcygsKzxk0NfuhXEKWagp1ewoXHaG43T0hXPmrecjUn0zTHmGHmcXhKcNFIY2BjECZfhi1ukGKpDuMO_OUXswb132LZfs40t-AijJ5eSSpnWPeHjaRbawPVyQMrkLYj95YAo5m3l') center/cover no-repeat;opacity:.9}.hero-grid{position:relative;z-index:2;display:grid;grid-template-columns:minmax(0,1.05fr) minmax(330px,.65fr);gap:18px;padding:26px;min-height:510px;align-items:start}.glass{background:rgba(255,255,255,.88);backdrop-filter:blur(16px);border:1px solid rgba(6,182,212,.75);box-shadow:var(--shadow-lg);border-radius:20px;padding:22px}.insight-title{display:flex;align-items:center;gap:10px;font-size:20px;font-weight:800}.insight-title .material-symbols-outlined{color:#00687a}.insight-copy{color:#3f4e4c;line-height:1.7;font-size:13px;margin:12px 0}.disclaimer{font-size:10px;color:#586866;font-style:italic}.hero-side{margin-left:auto;width:100%;display:grid;gap:10px}.bio-card{background:rgba(255,255,255,.88);backdrop-filter:blur(12px);border:1px solid rgba(188,201,198,.85);border-radius:16px;padding:14px 15px;display:flex;justify-content:space-between;align-items:center}.bio-card span:first-child{font-size:10px;color:var(--muted)}.bio-card strong{font-size:14px;font-variant-numeric:tabular-nums}.bio-card.ai{border-color:#9ce9f5;background:rgba(239,252,255,.92)}
    .notice{margin:18px 0 0;padding:12px 14px;border-radius:13px;background:#fff8e6;border:1px solid #f0dfb5;color:#654b0f;font-size:10.5px;display:flex;gap:9px;line-height:1.5}.notice strong{color:#4c380a}
    .two-col{grid-template-columns:minmax(0,1.55fr) minmax(320px,.68fr)}.three-col{grid-template-columns:repeat(3,minmax(0,1fr))}.four-col{grid-template-columns:repeat(4,minmax(0,1fr))}.twin-grid{grid-template-columns:minmax(380px,.88fr) minmax(0,1.12fr)}
    .panel-head{padding:17px 19px;border-bottom:1px solid #e8efed;display:flex;align-items:center;justify-content:space-between;gap:12px}.panel-body{padding:18px}.chart{min-height:370px;display:flex;align-items:center}.chart svg{width:100%;height:355px;overflow:visible}.chart.small{min-height:290px}.chart.small svg{height:275px}.legend{display:flex;align-items:center;gap:12px;color:var(--muted);font-size:9.5px;font-weight:700}.legend-item{display:flex;align-items:center;gap:6px}.legend-line{width:20px;height:3px;border-radius:4px;background:#00685f}.legend-line.cyan{background:#06b6d4}.legend-line.gray{background:#86938f}.legend-line.dash{height:0;border-top:2px dashed #06b6d4;background:transparent}
    .control-group{margin-bottom:17px}.control-label{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:7px;font-size:10.5px;color:#3b4b48;font-weight:700}.control-value{color:var(--primary);font-weight:800}.range{width:100%;accent-color:var(--primary)}select,input[type="number"]{width:100%;border:1px solid #cdd8d5;border-radius:12px;background:#fff;padding:10px 11px;color:var(--ink);outline:none}select:focus,input:focus{border-color:var(--primary2);box-shadow:0 0 0 3px rgba(0,131,120,.09)}
    .btn{border:0;border-radius:12px;padding:11px 14px;font-weight:800;font-size:11px;transition:.15s ease;display:inline-flex;align-items:center;justify-content:center;gap:7px}.btn.primary{background:var(--primary);color:white;box-shadow:0 8px 18px rgba(0,104,95,.18)}.btn.primary:hover{transform:translateY(-1px);background:#005b54}.btn.secondary{background:var(--primary-soft);color:var(--primary);border:1px solid #c8e3de}.btn.ghost{background:white;color:#42514f;border:1px solid var(--line)}.btn.full{width:100%}
    .impact-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:14px}.impact{background:#f7faf9;border:1px solid #e2ebe8;border-radius:13px;padding:11px}.impact span{font-size:9px;color:var(--muted);display:block}.impact strong{font-size:15px;margin-top:4px;display:block}.impact.good strong{color:var(--green)}
    .twin-visual{position:relative;min-height:610px;overflow:hidden;background:linear-gradient(180deg,#f8fbfb,#eef6f4)}.twin-visual .twin-bg{position:absolute;inset:0;background:url('https://lh3.googleusercontent.com/aida-public/AB6AXuCW0os3QWQcwbiInjkNX_Q0HychulLfJqQLxRmd157u6FxBjuayEzCXtUag6JSgMJxjBT_mIN2AKbORXOp_wQUWE1LCpiTaSI7645rd-WUmoGWyftnAenDybmNSCyMJlZJK59RlQyJe1Outny3uWio1WjietMdgjXTwsf0PbV7lLAJcS8Z5rUgUPyaZvLoxQjx9YP3aD1d-RcjNv6KQLQqzkx5irdy2_kocr8NzkpHH0LuK_zBm_rPp') center/cover no-repeat;opacity:.72}.twin-score{position:absolute;left:22px;bottom:22px;width:170px;height:170px;border-radius:50%;background:conic-gradient(var(--primary) 0 87%,#d9e4e1 87%);display:grid;place-items:center;box-shadow:var(--shadow-lg)}.twin-score:before{content:"";position:absolute;width:138px;height:138px;background:white;border-radius:50%}.twin-score-content{position:relative;text-align:center}.twin-score-content strong{display:block;font-size:31px;color:var(--primary)}.twin-score-content span{font-size:9px;color:var(--muted);font-weight:700}
    .parameter-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.param{padding:13px 14px;border:1px solid #e0e9e6;border-radius:14px;background:#fbfdfd}.param-top{display:flex;justify-content:space-between;gap:10px;font-size:10px;color:var(--muted)}.param strong{font-size:16px;color:#273633}.meter{height:6px;background:#e8efed;border-radius:999px;margin-top:9px;overflow:hidden}.meter>span{display:block;height:100%;border-radius:999px;background:linear-gradient(90deg,var(--primary),var(--cyan))}
    .timeline{display:flex;gap:0;align-items:stretch;margin-top:18px}.timeline-step{position:relative;flex:1;padding-top:20px;text-align:center;color:var(--muted);font-size:9px}.timeline-step:before{content:"";position:absolute;top:5px;left:0;right:0;height:2px;background:#d7e2df}.timeline-step:first-child:before{left:50%}.timeline-step:last-child:before{right:50%}.timeline-step .node{position:absolute;top:0;left:50%;transform:translateX(-50%);width:12px;height:12px;border-radius:50%;background:white;border:3px solid var(--primary)}.timeline-step.done .node{background:var(--primary)}
    .tir-stack{display:flex;height:28px;border-radius:999px;overflow:hidden;background:#e8eceb}.tir-seg{height:100%;display:grid;place-items:center;font-size:8px;font-weight:800;min-width:2px}.very-low{background:#a9001b;color:white}.low{background:#e76d64;color:white}.range-ok{background:#51b874;color:white}.high{background:#e7a93d;color:#3a2a00}.very-high{background:#bd641f;color:white}.goal-grid{grid-template-columns:repeat(5,minmax(0,1fr))}.goal{padding:15px;text-align:center}.goal strong{display:block;font-size:20px}.goal span{font-size:9px;color:var(--muted)}
    .patient-hero{display:grid;grid-template-columns:170px minmax(0,1fr) 240px;gap:18px;align-items:center}.patient-orb{width:140px;height:140px;border-radius:50%;background:radial-gradient(circle at 35% 25%,#bdf5ed,#48b7aa 55%,#00685f);box-shadow:0 20px 50px rgba(0,104,95,.18);display:grid;place-items:center;color:white;font-size:31px;font-weight:800}.patient-main h2{font-size:27px;margin:0 0 4px}.patient-meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.confidence{padding:18px;border-radius:17px;background:linear-gradient(135deg,#eefaf8,#ecfbff);border:1px solid #cce8e3;text-align:center}.confidence strong{font-size:34px;color:var(--primary)}.confidence span{display:block;font-size:9px;color:var(--muted);margin-top:4px}
    .info-list{display:grid;gap:0}.info-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 0;border-bottom:1px solid #e8efed;font-size:10.5px}.info-row:last-child{border-bottom:0}.info-row span{color:var(--muted)}.info-row strong{text-align:right}.data-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.data-card{padding:18px}.data-icon{width:38px;height:38px;border-radius:12px;background:var(--primary-soft);color:var(--primary);display:grid;place-items:center;margin-bottom:13px}.data-card h3{font-size:13px;margin:0 0 7px}.data-card p{font-size:10px;color:var(--muted);line-height:1.5;margin:0 0 13px}.status-line{display:flex;align-items:center;justify-content:space-between;font-size:9.5px}.status-ok{color:var(--green);font-weight:800}.status-research{color:var(--amber);font-weight:800}
    .governance-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.governance-card{padding:19px}.governance-card .material-symbols-outlined{width:38px;height:38px;border-radius:12px;background:#eff4f3;color:var(--primary);display:grid;place-items:center;margin-bottom:13px}.governance-card h3{font-size:14px;margin:0 0 8px}.governance-card p{font-size:10.5px;color:var(--muted);line-height:1.55;margin:0}.limit-list{margin:12px 0 0;padding-left:17px;color:#495956;font-size:10px;line-height:1.65}
    .benchmark-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.bench{padding:18px}.bench span{font-size:9.5px;color:var(--muted)}.bench strong{display:block;font-size:26px;letter-spacing:-.04em;margin-top:7px}.bench small{font-size:9px;color:var(--muted)}.compare-bar{height:32px;border-radius:10px;background:#eef2f1;position:relative;overflow:hidden;margin-top:12px}.compare-fill{position:absolute;left:0;top:0;bottom:0;background:linear-gradient(90deg,#78d5ca,#06b6d4);border-radius:10px}.compare-label{position:relative;z-index:2;display:flex;align-items:center;justify-content:space-between;height:100%;padding:0 10px;font-size:9.5px;font-weight:800;color:#173b39}
    .toast{position:fixed;right:22px;bottom:22px;z-index:80;background:#1e2b29;color:white;padding:11px 15px;border-radius:12px;box-shadow:0 15px 35px rgba(0,0,0,.2);font-size:11px;opacity:0;transform:translateY(8px);pointer-events:none;transition:.18s ease}.toast.show{opacity:1;transform:none}.loading{opacity:.55;pointer-events:none}
    .mobile-top{display:none}.mobile-nav{display:none}
    @media(max-width:1180px){.kpi-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.two-col,.twin-grid{grid-template-columns:1fr}.hero-grid{grid-template-columns:1fr}.hero-side{grid-template-columns:repeat(3,1fr)}.governance-grid,.data-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.patient-hero{grid-template-columns:140px 1fr}.confidence{grid-column:1/-1}.benchmark-grid{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:820px){:root{--nav:0px}.sidebar,.topbar{display:none}.shell{margin-left:0}.mobile-top{position:sticky;top:0;z-index:50;height:62px;background:rgba(247,249,251,.92);backdrop-filter:blur(16px);border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 16px}.mobile-brand{display:flex;align-items:center;gap:9px;color:var(--primary);font-weight:800}.mobile-brand .logo{width:34px;height:34px;border-radius:11px;font-size:12px}.mobile-nav{display:grid;position:fixed;left:10px;right:10px;bottom:10px;height:62px;z-index:60;background:rgba(255,255,255,.94);backdrop-filter:blur(18px);border:1px solid var(--line);border-radius:20px;box-shadow:0 14px 35px rgba(15,23,42,.16);grid-template-columns:repeat(5,1fr);padding:6px}.mnav{border:0;background:transparent;border-radius:13px;color:#5c6967;display:grid;place-items:center;font-size:8px;font-weight:700}.mnav span{font-size:20px}.mnav.active{background:#dff8fb;color:#00687a}main{padding:20px 16px 92px}.page-head{align-items:flex-start;flex-direction:column}.page-head h1{font-size:27px}.head-actions{justify-content:flex-start}.kpi-grid{grid-template-columns:repeat(2,1fr)}.hero-overview,.hero-grid{min-height:540px}.hero-grid{padding:16px}.hero-side{grid-template-columns:1fr 1fr;margin-top:210px}.bio-card:last-child{grid-column:1/-1}.three-col,.four-col,.goal-grid,.governance-grid,.data-grid,.parameter-list,.benchmark-grid{grid-template-columns:1fr}.patient-hero{grid-template-columns:1fr;text-align:center}.patient-orb{margin:auto}.patient-meta{justify-content:center}.twin-visual{min-height:520px}.twin-score{width:140px;height:140px}.twin-score:before{width:112px;height:112px}.two-col{grid-template-columns:1fr}.chart{min-height:310px}.chart svg{height:300px}.impact-grid{grid-template-columns:1fr 1fr}.impact:last-child{grid-column:1/-1}.page-head p{font-size:12px}}
  </style>
</head>
<body>
<div class="app">
  <aside class="sidebar">
    <div class="brand"><div class="logo">DT</div><div><strong>DiabetesTwin-AI</strong><small>Metabolic Intelligence</small></div></div>
    <nav class="nav">
      <button class="nav-btn active" data-page="overview"><span class="material-symbols-outlined">dashboard</span>Overview</button>
      <button class="nav-btn" data-page="twin"><span class="material-symbols-outlined">biotech</span>My Digital Twin</button>
      <button class="nav-btn" data-page="glucose"><span class="material-symbols-outlined">query_stats</span>Glucose Intelligence</button>
      <button class="nav-btn" data-page="simulator"><span class="material-symbols-outlined">psychology</span>What-if Simulator</button>
      <button class="nav-btn" data-page="cgm"><span class="material-symbols-outlined">sensors</span>CGM Explorer</button>
      <button class="nav-btn" data-page="forecasting"><span class="material-symbols-outlined">timeline</span>AI Forecasting</button>
      <button class="nav-btn" data-page="patient"><span class="material-symbols-outlined">person</span>Patient 360</button>
      <button class="nav-btn" data-page="data"><span class="material-symbols-outlined">hub</span>Data & FHIR</button>
      <button class="nav-btn" data-page="governance"><span class="material-symbols-outlined">policy</span>Model Governance</button>
    </nav>
    <div class="side-foot">
      <button class="nav-btn" id="healthNav"><span class="material-symbols-outlined">api</span>API Status</button>
      <div class="side-status"><strong>Research prototype</strong><br/>No clinical validation · no dosing or medication recommendations.</div>
    </div>
  </aside>

  <div class="shell">
    <header class="mobile-top"><div class="mobile-brand"><div class="logo">DT</div>DiabetesTwin-AI</div><span class="sync-pill"><span class="dot"></span>Live</span></header>
    <header class="topbar"><div class="top-left"><span class="material-symbols-outlined">science</span><span>Predictive diabetes digital twin · research environment</span></div><div class="top-actions"><span class="sync-pill"><span class="dot"></span><span id="syncText">Synchronized</span></span><button class="icon-btn" title="Refresh" id="refreshAll"><span class="material-symbols-outlined">sync</span></button><a class="icon-btn" href="/docs" title="API docs"><span class="material-symbols-outlined">terminal</span></a><div class="avatar">DT</div></div></header>

    <main>
      <section class="page active" id="page-overview">
        <div class="page-head"><div><div class="eyebrow">Executive patient overview</div><h1>Good morning, Alex</h1><p>Your metabolic digital twin is synchronized and ready for a new scenario.</p></div><div class="head-actions"><span class="chip primary"><span class="dot"></span> Digital Twin synchronized</span><span class="chip">Last update <span id="lastUpdate">now</span></span></div></div>
        <div class="card hero-overview"><div class="hero-img"></div><div class="hero-grid"><div class="glass"><div class="insight-title"><span class="material-symbols-outlined">psychology</span>AI Twin Insight</div><p class="insight-copy" id="overviewInsight">Your virtual glucose profile is being calculated from the current phenotype and lifestyle scenario.</p><p class="disclaimer">Research prototype — model simulation, not medical advice or treatment guidance.</p></div><div class="hero-side"><div class="bio-card"><span>Current simulated glucose</span><strong id="heroGlucose">—</strong></div><div class="bio-card ai"><span>+30 min virtual trajectory</span><strong id="heroPrediction">—</strong></div><div class="bio-card"><span>Time in Range</span><strong id="heroTir">—</strong></div><div class="bio-card"><span>Variability</span><strong id="heroCv">—</strong></div><div class="bio-card"><span>Phenotype</span><strong id="heroPhenotype">Balanced</strong></div></div></div></div>
        <div class="notice"><span class="material-symbols-outlined">warning</span><div><strong>Research and education only.</strong> Simulation outputs and CGMacros research data must not be interpreted as diagnosis, medication guidance, insulin dosing, or individualized clinical targets.</div></div>
        <div class="grid kpi-grid">
          <article class="card kpi"><div class="kpi-label">Mean glucose <span>mg/dL</span></div><div class="kpi-value" id="ovMean">—</div><div class="kpi-sub" id="ovMeanDelta">vs reference</div></article>
          <article class="card kpi"><div class="kpi-label">Time in Range <span>70–180</span></div><div class="kpi-value" id="ovTir">—</div><div class="kpi-sub" id="ovTirDelta">vs reference</div></article>
          <article class="card kpi"><div class="kpi-label">Below Range <span>&lt;70</span></div><div class="kpi-value" id="ovTbr">—</div><div class="kpi-sub">Simulated samples</div></article>
          <article class="card kpi"><div class="kpi-label">Above Range <span>&gt;180</span></div><div class="kpi-value" id="ovTar">—</div><div class="kpi-sub">Simulated samples</div></article>
          <article class="card kpi"><div class="kpi-label">Variability <span>CV</span></div><div class="kpi-value" id="ovCv">—</div><div class="kpi-sub">Coefficient of variation</div></article>
          <article class="card kpi"><div class="kpi-label">Peak glucose <span>mg/dL</span></div><div class="kpi-value" id="ovPeak">—</div><div class="kpi-sub">Simulation maximum</div></article>
        </div>
        <div class="grid two-col"><article class="card"><div class="panel-head"><div><div class="section-title">Metabolic trajectory · 24 hours</div><div class="section-sub">Current digital twin versus reference lifestyle</div></div><div class="legend"><span class="legend-item"><span class="legend-line"></span>Current</span><span class="legend-item"><span class="legend-line gray"></span>Reference</span></div></div><div class="panel-body"><div class="chart" id="overviewChart"></div></div></article><article class="card card-pad"><div class="section-title">What drives today’s simulation?</div><div class="section-sub">Model inputs currently applied to Twin-01.</div><div class="info-list" style="margin-top:12px"><div class="info-row"><span>Breakfast carbs</span><strong id="summaryBreakfast">45 g</strong></div><div class="info-row"><span>Lunch carbs</span><strong id="summaryLunch">65 g</strong></div><div class="info-row"><span>Dinner carbs</span><strong id="summaryDinner">70 g</strong></div><div class="info-row"><span>Evening activity</span><strong id="summaryExercise">35 min</strong></div><div class="info-row"><span>Stress</span><strong id="summaryStress">25%</strong></div><div class="info-row"><span>Sleep</span><strong id="summarySleep">7.5 h</strong></div></div><button class="btn primary full" style="margin-top:16px" data-jump="simulator"><span class="material-symbols-outlined">auto_awesome</span>Explore What-if Simulator</button></article></div>
      </section>

      <section class="page" id="page-twin">
        <div class="page-head"><div><div class="eyebrow">My Digital Twin</div><h1>Your metabolic model, made visible.</h1><p>A transparent view of the synthetic physiology parameters driving the current simulation.</p></div><div class="head-actions"><span class="chip cyan">Twin Calibration 87%</span><span class="chip warn">Research model</span></div></div>
        <div class="grid twin-grid"><article class="card twin-visual"><div class="twin-bg"></div><div class="glass" style="position:absolute;left:22px;top:22px;right:22px;max-width:420px"><div class="insight-title" style="font-size:17px"><span class="material-symbols-outlined">biotech</span>Personalization state</div><p class="insight-copy">The current virtual patient combines phenotype presets, glucose baseline, carbohydrate response, activity sensitivity, stress response and circadian modulation.</p><span class="chip primary">Twin-01 · synchronized</span></div><div class="twin-score"><div class="twin-score-content"><strong>87%</strong><span>TWIN CALIBRATION</span></div></div></article>
          <div class="grid" style="align-content:start"><article class="card card-pad-lg"><div class="section-title">Twin Parameters</div><div class="section-sub">Editable parameters from the educational virtual-patient model.</div><div class="parameter-list" style="margin-top:16px"><div class="param"><div class="param-top"><span>Baseline glucose</span><strong id="tpBaseline">112</strong></div><div class="meter"><span id="tmBaseline" style="width:44%"></span></div></div><div class="param"><div class="param-top"><span>Carbohydrate sensitivity</span><strong id="tpCarb">0.72</strong></div><div class="meter"><span id="tmCarb" style="width:38%"></span></div></div><div class="param"><div class="param-top"><span>Activity sensitivity</span><strong id="tpActivity">18</strong></div><div class="meter"><span id="tmActivity" style="width:45%"></span></div></div><div class="param"><div class="param-top"><span>Stress sensitivity</span><strong id="tpStressSens">16</strong></div><div class="meter"><span id="tmStressSens" style="width:40%"></span></div></div><div class="param"><div class="param-top"><span>Circadian amplitude</span><strong id="tpCircadian">7</strong></div><div class="meter"><span id="tmCircadian" style="width:35%"></span></div></div><div class="param"><div class="param-top"><span>Phenotype</span><strong id="tpPhenotype">Balanced</strong></div><div class="meter"><span style="width:62%"></span></div></div></div></article>
            <article class="card card-pad-lg"><div class="section-title">Personalization journey</div><div class="section-sub">How the research twin gains context as more data sources are connected.</div><div class="timeline"><div class="timeline-step done"><span class="node"></span>Profile<br/>preset</div><div class="timeline-step done"><span class="node"></span>CGM<br/>history</div><div class="timeline-step done"><span class="node"></span>Lifestyle<br/>events</div><div class="timeline-step"><span class="node"></span>Longitudinal<br/>calibration</div><div class="timeline-step"><span class="node"></span>Clinical<br/>validation</div></div></article>
            <article class="card card-pad"><div class="section-title">Twin controls</div><div class="section-sub">Switch the phenotype used by every simulated screen.</div><div class="control-group" style="margin-top:14px"><label class="control-label"><span>Phenotype preset</span><span class="control-value" id="twinPhenotypeValue">Balanced</span></label><select id="twinPhenotype"><option value="balanced">Balanced</option><option value="insulin_resistant">Insulin resistant</option><option value="active">Active</option></select></div><button class="btn primary" id="applyTwin"><span class="material-symbols-outlined">sync_alt</span>Apply to Digital Twin</button></article></div>
        </div>
      </section>

      <section class="page" id="page-glucose">
        <div class="page-head"><div><div class="eyebrow">Glucose Intelligence</div><h1>Time in Range, without the noise.</h1><p>Explore the standardized CGM display ranges for the selected research participant.</p></div><div class="head-actions"><span class="chip primary" id="tirParticipantChip">Participant 001</span><span class="chip">CGMacros v1.0.0</span></div></div>
        <article class="card card-pad-lg"><div class="section-title">Observed glucose distribution</div><div class="section-sub">Five-level CGM range breakdown. Individual targets require a healthcare professional.</div><div class="tir-stack" style="margin-top:22px"><div class="tir-seg very-low" id="segVL" style="width:1%"></div><div class="tir-seg low" id="segLow" style="width:3%"></div><div class="tir-seg range-ok" id="segTir" style="width:70%">70–180</div><div class="tir-seg high" id="segHigh" style="width:21%"></div><div class="tir-seg very-high" id="segVH" style="width:5%"></div></div><div class="grid goal-grid" style="margin-top:16px"><div class="card soft goal"><strong id="tirVL">—</strong><span>Very Low &lt;54</span></div><div class="card soft goal"><strong id="tirLow">—</strong><span>Low &lt;70</span></div><div class="card soft goal"><strong id="tirTarget">—</strong><span>Target 70–180</span></div><div class="card soft goal"><strong id="tirHigh">—</strong><span>High &gt;180</span></div><div class="card soft goal"><strong id="tirVH">—</strong><span>Very High &gt;250</span></div></div></article>
        <div class="grid two-col" style="margin-top:14px"><article class="card"><div class="panel-head"><div><div class="section-title">48-hour CGM trace</div><div class="section-sub">Privacy-shifted timestamps from the released dataset</div></div><div class="legend"><span class="legend-item"><span class="legend-line"></span>Observed CGM</span></div></div><div class="panel-body"><div class="chart" id="tirChart"></div></div></article><article class="card card-pad"><div class="section-title">Range interpretation</div><div class="section-sub">Standardized display ranges used for research reporting.</div><div class="info-list" style="margin-top:12px"><div class="info-row"><span>Observed mean</span><strong id="tirMean">—</strong></div><div class="info-row"><span>Variability</span><strong id="tirCv">—</strong></div><div class="info-row"><span>Minimum</span><strong id="tirMin">—</strong></div><div class="info-row"><span>Maximum</span><strong id="tirMax">—</strong></div><div class="info-row"><span>Data window</span><strong id="tirWindow">—</strong></div></div><div class="notice"><span class="material-symbols-outlined">info</span><div>These metrics describe released research data and are not individualized clinical targets.</div></div></article></div>
      </section>

      <section class="page" id="page-simulator">
        <div class="page-head"><div><div class="eyebrow">What-if Simulator</div><h1>Explore a metabolic future.</h1><p>Change lifestyle variables and compare the virtual trajectory with the reference scenario.</p></div><div class="head-actions"><button class="btn ghost" id="resetScenario"><span class="material-symbols-outlined">restart_alt</span>Reset</button><span class="chip cyan">Deterministic seed 42</span></div></div>
        <div class="grid two-col"><article class="card"><div class="panel-head"><div><div class="section-title">Before vs after · 24 hours</div><div class="section-sub">Reference lifestyle versus current simulated scenario</div></div><div class="legend"><span class="legend-item"><span class="legend-line gray"></span>Reference</span><span class="legend-item"><span class="legend-line cyan"></span>Scenario</span></div></div><div class="panel-body"><div class="chart" id="simChart"></div><div class="impact-grid"><div class="impact"><span>Peak change</span><strong id="impactPeak">—</strong></div><div class="impact good"><span>TIR change</span><strong id="impactTir">—</strong></div><div class="impact"><span>Mean change</span><strong id="impactMean">—</strong></div></div><div class="glass" style="margin-top:14px;box-shadow:none"><div class="insight-title" style="font-size:14px"><span class="material-symbols-outlined">lightbulb</span>Why did the curve move?</div><p class="insight-copy" id="scenarioExplanation" style="margin-bottom:0">Change a parameter and run the simulation to see an explainable model summary.</p></div></div></article>
          <aside class="card card-pad" id="scenarioControls"><div class="section-title">Scenario Builder</div><div class="section-sub">Lifestyle controls for the virtual patient.</div><div class="control-group" style="margin-top:18px"><label class="control-label"><span>Breakfast carbohydrates</span><span class="control-value" id="breakfastValue">45 g</span></label><input class="range" id="breakfast" type="range" min="0" max="120" step="5" value="45"/></div><div class="control-group"><label class="control-label"><span>Lunch carbohydrates</span><span class="control-value" id="lunchValue">65 g</span></label><input class="range" id="lunch" type="range" min="0" max="150" step="5" value="65"/></div><div class="control-group"><label class="control-label"><span>Dinner carbohydrates</span><span class="control-value" id="dinnerValue">70 g</span></label><input class="range" id="dinner" type="range" min="0" max="150" step="5" value="70"/></div><div class="control-group"><label class="control-label"><span>Evening activity</span><span class="control-value" id="exerciseValue">35 min</span></label><input class="range" id="exercise" type="range" min="0" max="90" step="5" value="35"/></div><div class="control-group"><label class="control-label"><span>Stress level</span><span class="control-value" id="stressValue">25%</span></label><input class="range" id="stress" type="range" min="0" max="100" step="5" value="25"/></div><div class="control-group"><label class="control-label"><span>Sleep duration</span><span class="control-value" id="sleepValue">7.5 h</span></label><input class="range" id="sleep" type="range" min="4" max="10" step="0.25" value="7.5"/></div><button class="btn primary full" id="simulateButton"><span class="material-symbols-outlined">auto_awesome</span>SIMULATE WITH MY DIGITAL TWIN</button></aside></div>
      </section>

      <section class="page" id="page-cgm">
        <div class="page-head"><div><div class="eyebrow">Real CGM Explorer</div><h1>Research data, connected to the twin.</h1><p>Explore the bundled licensed subset derived from PhysioNet CGMacros v1.0.0.</p></div><div class="head-actions"><span class="chip warn">CC BY-NC-SA 4.0</span><span class="chip">Privacy-shifted dates</span></div></div>
        <div class="grid two-col"><article class="card"><div class="panel-head"><div><div class="section-title">Participant glucose timeline</div><div class="section-sub">Released CGM trajectory · up to 48 hours</div></div><div class="control-group" style="margin:0;width:190px"><select id="participantSelect"><option value="001">Participant 001</option><option value="008">Participant 008</option><option value="003">Participant 003</option></select></div></div><div class="panel-body"><div class="chart" id="realChart"></div></div></article><aside class="card card-pad"><div style="display:flex;align-items:center;gap:13px"><div class="patient-orb" style="width:74px;height:74px;font-size:17px;box-shadow:none" id="participantAvatar">001</div><div><div class="section-title">CGMacros participant <span id="participantTitle">001</span></div><div class="section-sub">Pseudonymous released participant ID</div></div></div><div class="info-list" style="margin-top:15px"><div class="info-row"><span>Dataset group</span><strong id="realDiagnosis">—</strong></div><div class="info-row"><span>HbA1c</span><strong id="realHba1c">—</strong></div><div class="info-row"><span>Observed TIR</span><strong id="realTir">—</strong></div><div class="info-row"><span>Mean glucose</span><strong id="realMean">—</strong></div><div class="info-row"><span>Variability</span><strong id="realCv">—</strong></div><div class="info-row"><span>Displayed points</span><strong id="realPoints">—</strong></div></div><div class="notice"><span class="material-symbols-outlined">verified</span><div><strong>Data quality:</strong> bundled demo generated from the official checksum-verified CGMacros release.</div></div></aside></div>
      </section>

      <section class="page" id="page-forecasting">
        <div class="page-head"><div><div class="eyebrow">AI Glucose Forecasting</div><h1>Prediction performance, with the baseline visible.</h1><p>Verified +30 minute benchmark on participant-grouped holdout data.</p></div><div class="head-actions"><span class="chip cyan">+30 min horizon</span><span class="chip">45 participants</span></div></div>
        <div class="grid benchmark-grid"><article class="card bench"><span>Random Forest · MAE</span><strong>13.11</strong><small>mg/dL · unseen-participant holdout</small></article><article class="card bench"><span>Random Forest · RMSE</span><strong>18.94</strong><small>mg/dL · grouped participant holdout</small></article><article class="card bench"><span>Persistence · MAE</span><strong>13.39</strong><small>mg/dL · current glucose baseline</small></article><article class="card bench"><span>Usable forecast rows</span><strong>621,069</strong><small>45 / 45 participants</small></article></div>
        <div class="grid two-col" style="margin-top:14px"><article class="card"><div class="panel-head"><div><div class="section-title">Virtual forecast preview</div><div class="section-sub">Observed portion and +30 min digital-twin continuation from the synthetic engine</div></div><div class="legend"><span class="legend-item"><span class="legend-line"></span>Context</span><span class="legend-item"><span class="legend-line dash"></span>Future</span></div></div><div class="panel-body"><div class="chart" id="forecastChart"></div><div class="notice"><span class="material-symbols-outlined">science</span><div>This preview illustrates the interface using the synthetic twin. The verified real-data benchmark is reported separately above.</div></div></div></article><article class="card card-pad"><div class="section-title">Baseline comparison</div><div class="section-sub">The model only slightly improves MAE over persistence.</div><div style="margin-top:18px"><div class="info-row"><span>Persistence</span><strong>13.39 mg/dL</strong></div><div class="compare-bar"><div class="compare-fill" style="width:97.9%"></div><div class="compare-label"><span>Random Forest</span><span>13.11 mg/dL</span></div></div><div class="info-row"><span>Absolute MAE improvement</span><strong>0.28 mg/dL</strong></div><div class="info-row"><span>Relative improvement</span><strong>≈2.1%</strong></div></div><div class="glass" style="box-shadow:none;margin-top:16px"><div class="insight-title" style="font-size:14px"><span class="material-symbols-outlined">balance</span>Responsible interpretation</div><p class="insight-copy" style="margin-bottom:0">The grouped benchmark does not justify a strong performance claim. Persistence remains a very competitive baseline, and the system is not clinically validated.</p></div></article></div>
        <div class="card card-pad-lg" style="margin-top:14px"><div class="section-title">Prediction Drivers</div><div class="section-sub">Model input families used in the real-data forecasting pipeline. These are predictive features, not causal clinical explanations.</div><div class="parameter-list" style="margin-top:16px"><div class="param"><div class="param-top"><span>Current glucose</span><strong>High signal</strong></div><div class="meter"><span style="width:92%"></span></div></div><div class="param"><div class="param-top"><span>15/30 min glucose lags</span><strong>High signal</strong></div><div class="meter"><span style="width:86%"></span></div></div><div class="param"><div class="param-top"><span>Recent carbohydrates</span><strong>Context</strong></div><div class="meter"><span style="width:63%"></span></div></div><div class="param"><div class="param-top"><span>Time of day</span><strong>Context</strong></div><div class="meter"><span style="width:49%"></span></div></div><div class="param"><div class="param-top"><span>Heart rate / activity</span><strong>Context</strong></div><div class="meter"><span style="width:46%"></span></div></div><div class="param"><div class="param-top"><span>HbA1c / fasting labs</span><strong>Profile</strong></div><div class="meter"><span style="width:40%"></span></div></div></div></div>
      </section>

      <section class="page" id="page-patient">
        <div class="page-head"><div><div class="eyebrow">Patient 360</div><h1>One profile for metabolic context.</h1><p>Synthetic twin settings and released CGMacros demo attributes in one research view.</p></div><div class="head-actions"><span class="chip primary">Digital Twin active</span><span class="chip">Demo participant <span id="patientChipId">001</span></span></div></div>
        <article class="card card-pad-lg patient-hero"><div class="patient-orb">A</div><div class="patient-main"><div class="eyebrow">Synthetic demo patient</div><h2>Alex · Twin-01</h2><p class="section-sub">Personalized virtual-patient profile linked to CGMacros participant context for demonstration only.</p><div class="patient-meta"><span class="chip primary" id="patientDiagnosisChip">CGMacros group —</span><span class="chip cyan">+30 min research forecasting</span><span class="chip warn">Not clinically validated</span></div></div><div class="confidence"><strong>87%</strong><span>TWIN PERSONALIZATION COVERAGE</span></div></article>
        <div class="grid three-col" style="margin-top:14px"><article class="card card-pad"><div class="section-title">Metabolic profile</div><div class="info-list" style="margin-top:10px"><div class="info-row"><span>Age</span><strong>45 y · synthetic</strong></div><div class="info-row"><span>HbA1c</span><strong id="patientHba1c">—</strong></div><div class="info-row"><span>Baseline glucose</span><strong id="patientBaseline">112 mg/dL</strong></div><div class="info-row"><span>Phenotype</span><strong id="patientPhenotype">Balanced</strong></div></div></article><article class="card card-pad"><div class="section-title">Lifestyle scenario</div><div class="info-list" style="margin-top:10px"><div class="info-row"><span>Sleep</span><strong id="patientSleep">7.5 h</strong></div><div class="info-row"><span>Stress</span><strong id="patientStress">25%</strong></div><div class="info-row"><span>Activity</span><strong id="patientActivity">35 min</strong></div><div class="info-row"><span>Daily carbs</span><strong id="patientCarbs">180 g</strong></div></div></article><article class="card card-pad"><div class="section-title">CGM summary</div><div class="info-list" style="margin-top:10px"><div class="info-row"><span>Mean glucose</span><strong id="patientMean">—</strong></div><div class="info-row"><span>Observed TIR</span><strong id="patientTir">—</strong></div><div class="info-row"><span>Variability</span><strong id="patientCv">—</strong></div><div class="info-row"><span>Coverage</span><strong>≈48 h demo</strong></div></div></article></div>
        <article class="card card-pad-lg" style="margin-top:14px"><div class="section-title">What contributes to Twin Confidence?</div><div class="parameter-list" style="margin-top:15px"><div class="param"><div class="param-top"><span>Virtual patient parameters</span><strong>100%</strong></div><div class="meter"><span style="width:100%"></span></div></div><div class="param"><div class="param-top"><span>CGM demo history</span><strong>90%</strong></div><div class="meter"><span style="width:90%"></span></div></div><div class="param"><div class="param-top"><span>Lifestyle events</span><strong>82%</strong></div><div class="meter"><span style="width:82%"></span></div></div><div class="param"><div class="param-top"><span>Laboratory profile</span><strong>76%</strong></div><div class="meter"><span style="width:76%"></span></div></div></div><div class="notice"><span class="material-symbols-outlined">info</span><div>The 87% figure is a user-interface research coverage indicator, not a validated clinical confidence score or probability.</div></div></article>
      </section>

      <section class="page" id="page-data">
        <div class="page-head"><div><div class="eyebrow">Data & Interoperability</div><h1>Built to connect, built to explain.</h1><p>Explore APIs, FHIR demonstration export, research data provenance and deployment status.</p></div><div class="head-actions"><a class="btn ghost" href="/docs"><span class="material-symbols-outlined">description</span>OpenAPI docs</a><button class="btn primary" id="fhirButton"><span class="material-symbols-outlined">download</span>Export FHIR Bundle</button></div></div>
        <div class="grid data-grid"><article class="card data-card"><div class="data-icon"><span class="material-symbols-outlined">monitor_heart</span></div><h3>CGM demo data</h3><p>Bundled subset derived from PhysioNet CGMacros v1.0.0 with privacy-shifted released timestamps.</p><div class="status-line"><span>Source</span><strong class="status-ok">Connected</strong></div></article><article class="card data-card"><div class="data-icon"><span class="material-symbols-outlined">api</span></div><h3>REST API</h3><p>Typed FastAPI endpoints power the web interface without heavy server-side scientific dependencies on Vercel.</p><div class="status-line"><span>Runtime</span><strong class="status-ok" id="apiRuntime">Checking…</strong></div></article><article class="card data-card"><div class="data-icon"><span class="material-symbols-outlined">medical_information</span></div><h3>FHIR R5</h3><p>Demonstration Observation Bundle using glucose LOINC 15074-8 and UCUM mg/dL units.</p><div class="status-line"><span>Export</span><strong class="status-ok">Enabled</strong></div></article><article class="card data-card"><div class="data-icon"><span class="material-symbols-outlined">license</span></div><h3>Dataset provenance</h3><p>CGMacros demo derivative remains under CC BY-NC-SA 4.0; application source code is MIT.</p><div class="status-line"><span>Governance</span><strong class="status-research">Documented</strong></div></article></div>
        <div class="grid two-col" style="margin-top:14px"><article class="card card-pad-lg"><div class="section-title">API surface</div><div class="info-list" style="margin-top:12px"><div class="info-row"><span>Health</span><strong><code>GET /health</code></strong></div><div class="info-row"><span>Virtual simulation</span><strong><code>POST /simulate</code></strong></div><div class="info-row"><span>Real-data demo</span><strong><code>GET /demo/cgmacros</code></strong></div><div class="info-row"><span>FHIR observations</span><strong><code>POST /fhir/observations</code></strong></div><div class="info-row"><span>Swagger / OpenAPI</span><strong><code>GET /docs</code></strong></div></div></article><article class="card card-pad-lg"><div class="section-title">Data provenance</div><div class="section-sub">Research dataset facts shown explicitly in the product.</div><div class="info-list" style="margin-top:12px"><div class="info-row"><span>Dataset</span><strong>PhysioNet CGMacros v1.0.0</strong></div><div class="info-row"><span>DOI</span><strong>10.13026/3z8q-x658</strong></div><div class="info-row"><span>Full cohort</span><strong>45 participants</strong></div><div class="info-row"><span>Bundled demo</span><strong>3 participants · ≈48 h each</strong></div><div class="info-row"><span>Demo license</span><strong>CC BY-NC-SA 4.0</strong></div></div></article></div>
      </section>

      <section class="page" id="page-governance">
        <div class="page-head"><div><div class="eyebrow">AI / Model Governance</div><h1>Scientific transparency before performance theatre.</h1><p>Validation status, dataset provenance, model limits and responsible interpretation in one place.</p></div><div class="head-actions"><span class="chip warn">Research prototype</span><span class="chip">No regulatory claim</span></div></div>
        <div class="grid governance-grid"><article class="card governance-card"><span class="material-symbols-outlined">fact_check</span><h3>Validation status</h3><p>Software and research validation only. The system has not undergone clinical validation and must not be used for treatment decisions.</p></article><article class="card governance-card"><span class="material-symbols-outlined">database</span><h3>Dataset</h3><p>PhysioNet CGMacros v1.0.0. Full benchmark uses 45 participants; the deployment bundles a 3-participant licensed demo subset.</p></article><article class="card governance-card"><span class="material-symbols-outlined">analytics</span><h3>Evaluation</h3><p>Grouped holdout separates entire participants. The Random Forest MAE is 13.11 mg/dL versus 13.39 mg/dL for persistence.</p></article><article class="card governance-card"><span class="material-symbols-outlined">warning</span><h3>Known limitations</h3><ul class="limit-list"><li>Small cohort for generalization claims</li><li>No insulin or medication recommendation model</li><li>Persistence baseline remains highly competitive</li><li>Demo timestamps are privacy-shifted</li></ul></article><article class="card governance-card"><span class="material-symbols-outlined">balance</span><h3>Scientific vs clinical validation</h3><p>Scientific benchmark performance demonstrates a research workflow. It does not establish safety, efficacy, medical-device performance or regulatory approval.</p></article><article class="card governance-card"><span class="material-symbols-outlined">lock</span><h3>Responsible deployment</h3><p>The public demo avoids direct identifiers, uses released pseudonymous IDs, preserves dataset licensing and displays persistent research disclaimers.</p></article></div>
        <article class="card card-pad-lg" style="margin-top:14px"><div class="section-title">Model card snapshot</div><div class="grid four-col" style="margin-top:14px"><div class="param"><div class="param-top"><span>Best grouped model</span><strong>Random Forest</strong></div><div class="meter"><span style="width:68%"></span></div></div><div class="param"><div class="param-top"><span>MAE improvement</span><strong>0.28 mg/dL</strong></div><div class="meter"><span style="width:18%"></span></div></div><div class="param"><div class="param-top"><span>Participants</span><strong>45</strong></div><div class="meter"><span style="width:75%"></span></div></div><div class="param"><div class="param-top"><span>Clinical validation</span><strong>Not performed</strong></div><div class="meter"><span style="width:3%;background:var(--amber)"></span></div></div></div></article>
      </section>
    </main>

    <nav class="mobile-nav"><button class="mnav active" data-page="overview"><span class="material-symbols-outlined">dashboard</span>Overview</button><button class="mnav" data-page="twin"><span class="material-symbols-outlined">biotech</span>Twin</button><button class="mnav" data-page="simulator"><span class="material-symbols-outlined">psychology</span>Simulate</button><button class="mnav" data-page="cgm"><span class="material-symbols-outlined">sensors</span>CGM</button><button class="mnav" data-page="governance"><span class="material-symbols-outlined">more_horiz</span>More</button></nav>
  </div>
</div>
<div class="toast" id="toast"></div>
<script>
  const $ = id => document.getElementById(id);
  const presets = {
    balanced:{baseline_glucose:112,carb_sensitivity:.72,activity_sensitivity:18,stress_sensitivity:16,circadian_amplitude:7},
    insulin_resistant:{baseline_glucose:138,carb_sensitivity:1.05,activity_sensitivity:14,stress_sensitivity:22,circadian_amplitude:10},
    active:{baseline_glucose:102,carb_sensitivity:.58,activity_sensitivity:24,stress_sensitivity:13,circadian_amplitude:6}
  };
  const refScenario={breakfast:45,lunch:65,dinner:70,exercise:35,stress:.25,sleep:7.5};
  let activePhenotype='balanced', currentScenario={...refScenario}, referenceResult=null, currentResult=null, realData=null;
  const fmt=(n,d=0)=>Number(n).toFixed(d); const pct=n=>`${fmt(n,1)}%`; const signed=(n,d=1,s='')=>`${n>=0?'+':''}${fmt(n,d)}${s}`;
  function showToast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2800)}
  function titleCase(v){return String(v).replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
  function showPage(name){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${name}`));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));history.replaceState(null,'',`#${name}`);window.scrollTo({top:0,behavior:'smooth'});if(name==='forecasting')renderForecast();if(name==='glucose')renderRealAcrossPages();}
  document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.jump)));
  function scenarioFromUI(){return{breakfast:Number($('breakfast').value),lunch:Number($('lunch').value),dinner:Number($('dinner').value),exercise:Number($('exercise').value),stress:Number($('stress').value)/100,sleep:Number($('sleep').value)}}
  function payload(sc,phenotype=activePhenotype){const p=presets[phenotype];return{patient:{name:'Twin-01',age:45,phenotype,...p},scenario:{meals:[{hour:8,carbs_g:sc.breakfast,label:'Breakfast'},{hour:13,carbs_g:sc.lunch,label:'Lunch'},{hour:19.5,carbs_g:sc.dinner,label:'Dinner'}],exercise:sc.exercise>0?[{hour:18,duration_min:sc.exercise,intensity:.55,label:'Activity'}]:[],stress:sc.stress,sleep_hours:sc.sleep,sleep_quality:.8},seed:42,step_minutes:5}}
  async function simulate(sc,phenotype=activePhenotype){const r=await fetch('/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(sc,phenotype))});if(!r.ok)throw new Error(`Simulation failed (${r.status})`);return r.json()}
  function chartSvg(a,b=null,opt={}){if(!a||!a.length)return'<div style="padding:42px;color:#5b6664">No data available.</div>';const W=1000,H=350,L=52,R=18,T=18,B=42;const vals=a.map(d=>d.y).concat(b?b.map(d=>d.y):[]);const ymin=Math.min(50,Math.floor((Math.min(...vals)-15)/10)*10),ymax=Math.max(220,Math.ceil((Math.max(...vals)+18)/10)*10);const xmin=Math.min(...a.map(d=>d.x)),xmax=Math.max(...a.map(d=>d.x));const x=v=>L+(v-xmin)/(xmax-xmin||1)*(W-L-R),y=v=>T+(ymax-v)/(ymax-ymin)*(H-T-B);const path=s=>s.map((d,i)=>`${i?'L':'M'}${x(d.x).toFixed(1)},${y(d.y).toFixed(1)}`).join(' ');let h=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Glucose chart">`;h+=`<rect x="${L}" y="${y(180)}" width="${W-L-R}" height="${y(70)-y(180)}" fill="#eaf7ef" rx="5"/>`;[70,120,180,250].filter(v=>v>=ymin&&v<=ymax).forEach(v=>{h+=`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" stroke="#e4ebe9"/><text x="${L-9}" y="${y(v)+4}" text-anchor="end" font-size="10" fill="#6b7774">${v}</text>`});for(let i=0;i<6;i++){const q=i/5,v=xmin+(xmax-xmin)*q,xp=x(v);let label=opt.timeMode?clockLabel(q,opt.start,opt.end):`${Math.round(v)}h`;h+=`<text x="${xp}" y="${H-15}" text-anchor="middle" font-size="9" fill="#6b7774">${label}</text>`}if(!opt.timeMode){[8,13,19.5].forEach((hr,idx)=>{const xp=x(hr);h+=`<line x1="${xp}" x2="${xp}" y1="${T}" y2="${H-B}" stroke="#9eaaa7" stroke-dasharray="3 5" opacity=".6"/><text x="${xp+4}" y="${T+12}" font-size="8.5" fill="#6b7774">${['Breakfast','Lunch','Dinner'][idx]}</text>`})}if(b)h+=`<path d="${path(b)}" fill="none" stroke="#87928f" stroke-width="2.2" stroke-dasharray="6 6" stroke-linecap="round"/>`;h+=`<path d="${path(a)}" fill="none" stroke="${opt.cyan?'#06b6d4':'#00685f'}" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>`;if(opt.forecastIndex!=null){const xp=x(a[opt.forecastIndex].x);h+=`<line x1="${xp}" x2="${xp}" y1="${T}" y2="${H-B}" stroke="#00687a" stroke-dasharray="4 4"/><text x="${xp+5}" y="${T+12}" font-size="9" fill="#00687a">Now</text>`}h+=`<text x="${L}" y="12" font-size="9" fill="#6b7774">mg/dL</text></svg>`;return h}
  function clockLabel(r,start,end){if(!start||!end)return`${Math.round(r*48)}h`;const s=new Date(start),e=new Date(end),d=new Date(s.getTime()+r*(e-s));return d.toLocaleString([],{month:'short',day:'numeric',hour:'2-digit'})}
  function updateScenarioLabels(){const sc=scenarioFromUI();currentScenario=sc;$('breakfastValue').textContent=`${sc.breakfast} g`;$('lunchValue').textContent=`${sc.lunch} g`;$('dinnerValue').textContent=`${sc.dinner} g`;$('exerciseValue').textContent=`${sc.exercise} min`;$('stressValue').textContent=`${Math.round(sc.stress*100)}%`;$('sleepValue').textContent=`${sc.sleep} h`;['summaryBreakfast','summaryLunch','summaryDinner'].forEach((id,i)=>$(id).textContent=`${[sc.breakfast,sc.lunch,sc.dinner][i]} g`);$('summaryExercise').textContent=`${sc.exercise} min`;$('summaryStress').textContent=`${Math.round(sc.stress*100)}%`;$('summarySleep').textContent=`${sc.sleep} h`;$('patientSleep').textContent=`${sc.sleep} h`;$('patientStress').textContent=`${Math.round(sc.stress*100)}%`;$('patientActivity').textContent=`${sc.exercise} min`;$('patientCarbs').textContent=`${sc.breakfast+sc.lunch+sc.dinner} g`}
  ['breakfast','lunch','dinner','exercise','stress','sleep'].forEach(id=>$(id).addEventListener('input',updateScenarioLabels));
  function setTwinUI(){const p=presets[activePhenotype];$('heroPhenotype').textContent=titleCase(activePhenotype);$('tpBaseline').textContent=p.baseline_glucose;$('tpCarb').textContent=p.carb_sensitivity.toFixed(2);$('tpActivity').textContent=p.activity_sensitivity;$('tpStressSens').textContent=p.stress_sensitivity;$('tpCircadian').textContent=p.circadian_amplitude;$('tpPhenotype').textContent=titleCase(activePhenotype);$('twinPhenotypeValue').textContent=titleCase(activePhenotype);$('patientBaseline').textContent=`${p.baseline_glucose} mg/dL`;$('patientPhenotype').textContent=titleCase(activePhenotype);$('tmBaseline').style.width=`${Math.min(100,p.baseline_glucose/190*100)}%`;$('tmCarb').style.width=`${Math.min(100,p.carb_sensitivity/1.5*100)}%`;$('tmActivity').style.width=`${Math.min(100,p.activity_sensitivity/40*100)}%`;$('tmStressSens').style.width=`${Math.min(100,p.stress_sensitivity/40*100)}%`;$('tmCircadian').style.width=`${Math.min(100,p.circadian_amplitude/25*100)}%`}
  async function runSimulation(initial=false){const c=$('scenarioControls');if(c)c.classList.add('loading');try{referenceResult=await simulate(refScenario);currentScenario=scenarioFromUI();currentResult=await simulate(currentScenario);renderSimulation();if(!initial)showToast('Digital Twin scenario updated.')}catch(e){showToast(e.message)}finally{if(c)c.classList.remove('loading')}}
  function renderSimulation(){if(!currentResult||!referenceResult)return;const m=currentResult.metrics,r=referenceResult.metrics;const last=currentResult.points[currentResult.points.length-1],forecast=currentResult.points.find(p=>p.minute===30)||currentResult.points[Math.min(6,currentResult.points.length-1)];$('heroGlucose').textContent=`${fmt(last.glucose_mg_dl)} mg/dL`;$('heroPrediction').textContent=`${fmt(forecast.glucose_mg_dl)} mg/dL`;$('heroTir').textContent=pct(m.time_in_range_pct);$('heroCv').textContent=pct(m.coefficient_of_variation_pct);$('ovMean').textContent=fmt(m.mean_glucose);$('ovTir').textContent=pct(m.time_in_range_pct);$('ovTbr').textContent=pct(m.time_below_range_pct);$('ovTar').textContent=pct(m.time_above_range_pct);$('ovCv').textContent=pct(m.coefficient_of_variation_pct);$('ovPeak').textContent=fmt(m.max_glucose);$('ovMeanDelta').textContent=`${signed(m.mean_glucose-r.mean_glucose,1,' mg/dL')} vs reference`;$('ovTirDelta').textContent=`${signed(m.time_in_range_pct-r.time_in_range_pct,1,' pp')} vs reference`;$('impactPeak').textContent=signed(m.max_glucose-r.max_glucose,1,' mg/dL');$('impactTir').textContent=signed(m.time_in_range_pct-r.time_in_range_pct,1,' pp');$('impactMean').textContent=signed(m.mean_glucose-r.mean_glucose,1,' mg/dL');const a=currentResult.points.map(p=>({x:p.hour,y:p.glucose_mg_dl})),b=referenceResult.points.map(p=>({x:p.hour,y:p.glucose_mg_dl}));$('overviewChart').innerHTML=chartSvg(a,b);$('simChart').innerHTML=chartSvg(a,b,{cyan:true});renderForecast();const dCarbs=currentScenario.breakfast+currentScenario.lunch+currentScenario.dinner-(refScenario.breakfast+refScenario.lunch+refScenario.dinner),dExercise=currentScenario.exercise-refScenario.exercise,dStress=currentScenario.stress-refScenario.stress;let factors=[];if(Math.abs(dCarbs)>=10)factors.push(`${dCarbs>0?'Higher':'Lower'} total carbohydrate load changes post-meal excursions.`);if(Math.abs(dExercise)>=10)factors.push(`${dExercise>0?'More':'Less'} evening activity changes the simulated glucose-lowering effect.`);if(Math.abs(dStress)>=.1)factors.push(`${dStress>0?'Higher':'Lower'} stress changes the modelled stress offset.`);if(!factors.length)factors.push('The current controls are close to the reference lifestyle, so the two trajectories remain similar.');$('scenarioExplanation').textContent=factors.slice(0,2).join(' ');$('overviewInsight').textContent=m.time_in_range_pct>=70?`The current virtual profile remains predominantly within the standardized 70–180 mg/dL display range. The modelled peak is ${fmt(m.max_glucose)} mg/dL with ${pct(m.time_in_range_pct)} time in range.`:`The current virtual profile spends ${pct(m.time_in_range_pct)} in the standardized display range. Explore the What-if Simulator to compare lifestyle scenarios.`;$('lastUpdate').textContent='just now'}
  function renderForecast(){if(!currentResult||!$('forecastChart'))return;const pts=currentResult.points;const start=Math.max(0,pts.length-48),now=Math.max(start+1,pts.length-7),slice=pts.slice(start);const series=slice.map(p=>({x:p.hour,y:p.glucose_mg_dl}));const nowIdx=now-start;$('forecastChart').innerHTML=chartSvg(series,null,{cyan:true,forecastIndex:nowIdx})}
  async function loadRealData(id='001'){try{const r=await fetch(`/demo/cgmacros?participant_id=${encodeURIComponent(id)}&max_points=700`);if(!r.ok)throw new Error('CGMacros demo unavailable');realData=await r.json();renderRealAcrossPages()}catch(e){showToast(e.message);['realChart','tirChart'].forEach(id=>{if($(id))$(id).innerHTML=`<div style="padding:42px;color:#ba1a1a">${e.message}</div>`})}}
  function renderRealAcrossPages(){if(!realData)return;const d=realData,m=d.metrics,series=d.points.map((p,i)=>({x:i,y:p.glucose_mg_dl}));$('realChart').innerHTML=chartSvg(series,null,{timeMode:true,start:d.start,end:d.end});$('tirChart').innerHTML=chartSvg(series,null,{timeMode:true,start:d.start,end:d.end});$('participantAvatar').textContent=d.participant_id;$('participantTitle').textContent=d.participant_id;$('realDiagnosis').textContent=d.diagnosis_label;$('realHba1c').textContent=d.hba1c==null?'n/a':`${Number(d.hba1c).toFixed(1)}%`;$('realTir').textContent=pct(m.time_in_range_pct);$('realMean').textContent=`${fmt(m.mean_glucose,1)} mg/dL`;$('realCv').textContent=pct(m.coefficient_of_variation_pct);$('realPoints').textContent=d.points.length.toLocaleString();$('tirParticipantChip').textContent=`Participant ${d.participant_id}`;$('tirTarget').textContent=pct(m.time_in_range_pct);$('tirLow').textContent=pct(m.time_below_range_pct);$('tirHigh').textContent=pct(m.time_above_range_pct);$('tirVL').textContent=pct(m.time_very_low_pct);$('tirVH').textContent=pct(m.time_very_high_pct);$('tirMean').textContent=`${fmt(m.mean_glucose,1)} mg/dL`;$('tirCv').textContent=pct(m.coefficient_of_variation_pct);$('tirMin').textContent=`${fmt(m.min_glucose,1)} mg/dL`;$('tirMax').textContent=`${fmt(m.max_glucose,1)} mg/dL`;$('tirWindow').textContent='≈48 h demo';$('patientChipId').textContent=d.participant_id;$('patientDiagnosisChip').textContent=`CGMacros group · ${d.diagnosis_label}`;$('patientHba1c').textContent=d.hba1c==null?'n/a':`${Number(d.hba1c).toFixed(1)}%`;$('patientMean').textContent=`${fmt(m.mean_glucose,1)} mg/dL`;$('patientTir').textContent=pct(m.time_in_range_pct);$('patientCv').textContent=pct(m.coefficient_of_variation_pct);const lowOnly=Math.max(0,m.time_below_range_pct-m.time_very_low_pct),highOnly=Math.max(0,m.time_above_range_pct-m.time_very_high_pct);const widths={vl:m.time_very_low_pct,l:lowOnly,t:m.time_in_range_pct,h:highOnly,vh:m.time_very_high_pct};$('segVL').style.width=`${Math.max(.4,widths.vl)}%`;$('segLow').style.width=`${Math.max(.4,widths.l)}%`;$('segTir').style.width=`${Math.max(.4,widths.t)}%`;$('segHigh').style.width=`${Math.max(.4,widths.h)}%`;$('segVH').style.width=`${Math.max(.4,widths.vh)}%`}
  async function checkHealth(){try{const r=await fetch('/health');const d=await r.json();$('syncText').textContent='Synchronized';$('apiRuntime').textContent=d.runtime||'Online'}catch(e){$('syncText').textContent='API issue';if($('apiRuntime'))$('apiRuntime').textContent='Unavailable'}}
  async function downloadFhir(){try{const r=await fetch('/fhir/observations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(currentScenario))});if(!r.ok)throw new Error('FHIR export failed');const data=await r.json(),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/fhir+json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='diabetestwin_fhir_bundle.json';a.click();URL.revokeObjectURL(url);showToast('FHIR Bundle downloaded.')}catch(e){showToast(e.message)}}
  $('simulateButton').addEventListener('click',()=>runSimulation(false));$('resetScenario').addEventListener('click',()=>{Object.entries(refScenario).forEach(([k,v])=>{if($(k))$(k).value=k==='stress'?v*100:v});updateScenarioLabels();runSimulation(false)});$('participantSelect').addEventListener('change',e=>loadRealData(e.target.value));$('applyTwin').addEventListener('click',()=>{activePhenotype=$('twinPhenotype').value;setTwinUI();runSimulation(false);showToast(`${titleCase(activePhenotype)} phenotype applied.`)});$('twinPhenotype').addEventListener('change',e=>$('twinPhenotypeValue').textContent=titleCase(e.target.value));$('fhirButton').addEventListener('click',downloadFhir);$('refreshAll').addEventListener('click',()=>Promise.all([checkHealth(),runSimulation(true),loadRealData($('participantSelect').value)]).then(()=>showToast('Digital Twin synchronized.')));$('healthNav').addEventListener('click',()=>fetch('/health').then(r=>r.json()).then(d=>showToast(`API ${d.status} · ${d.runtime}`)).catch(()=>showToast('API unavailable')));
  updateScenarioLabels();setTwinUI();const initialHash=location.hash.replace('#','');if(['overview','twin','glucose','simulator','cgm','forecasting','patient','data','governance'].includes(initialHash))showPage(initialHash);Promise.all([checkHealth(),runSimulation(true),loadRealData('001')]);
</script>
</body>
</html>'''
